### ISSUE TITLE
Is it necessary to create new instances on the grains exercise?

### ISSUE THREAD

**Issue by StevenXL** [exercism/xruby#113]
The new instances created by the grains exercise are all exactly alike. 

Is it a better idea to make the methods class methods (instead of instance methods), and change the tests appropriately? This would keep the exercise consistent with the other exercises by testing class methods. Or am I missing the reason for having instances that are exactly the same? 

If you agree with the logic of this, I can go ahead and change the exercise.

**Comment by kotp** [comment]
Links to the files you are referencing would be nice :)

[Grains](https://github.com/exercism/xruby/tree/master/grains) exercise tests are definitely modifiable.  And should not effect any solutions that I am aware of.  The [example.rb](https://github.com/exercism/xruby/blob/master/grains/example.rb) file uses a Class for no obvious (to me) reason.  The tests use `.new` rather than `.allocate` which it could very well do.

The test also has a lot of duplication, where the actual object could be stored and reused.

My suggestion is go ahead and work up a pull request.  It will exhibit your thoughts even more completely than a paragraph of words.

Worst thing that can happen is people talk about it and it doesn't get accepted.

**Comment by StevenXL** [comment]
Thanks @kotp. I'm still new to this whole thing - forgive the lack of links. 

I'll do as you suggested and work up a pull request and move the conversation there. Thanks!
