### ISSUE TITLE
Inconsistencies on the «Series» exercise

### ISSUE THREAD

**Issue by Rojo** [exercism/xruby#244]
* The README for this exercise does not reflect that all the generated slices should be returned if no series is found among them.
* The tests https://github.com/exercism/xruby/blob/master/exercises/series/series_test.rb#L24 and https://github.com/exercism/xruby/blob/master/exercises/series/series_test.rb#L49 include one series among them, yet the expected outcome is as if no series were found.

**Comment by kytrinyx** [comment]
I'm not sure what the right move is here. The READMEs are generally pretty vague on purpose, and the tests are considered the source of truth, but if the README could be improved without making it wrong for other languages, that's generally a plus.

**Comment by petertseng** [comment]
I think the confusion here is simply that the series need not be consecutive.

**Comment by kytrinyx** [comment]
Ahh, yes. Thank you--that's definitely the way to go.

**Comment by Rojo** [comment]
@kytrinyx, @petertseng Nice! But what about the mentioned tests? Is that the expected behaviour?

**Comment by petertseng** [comment]
I'm backtracking on what I said earlier. Look at http://x.exercism.io/problems/series - it wants the **consecutive** series. So most of the tests in ruby track are inconsistent with this description, and probably many other tracks as well -- would have to survey all the tracks appearing in the above list to see the extent of the "damage". I suggest that now would be a great time to add shared test data to https://github.com/exercism/x-common in the form of series.json and get that sorted out in the various tracks.

**Comment by petertseng** [comment]
I'm backtracking on what I said earlier. Look at http://x.exercism.io/problems/series - it wants the **consecutive** series. Does that just mean the *positions* have to be consecutive, or do the *numbers* have to be consecutive too (in addition to the positions)?

Most of the tests in ruby track are  consistent with *only the positions* being consecutive. Probably many other tracks as well -- would have to survey all the tracks appearing in the above list to see the extent of the "damage".
I am guessing the creator of the problem just wanted *positions*, since it's claimed to be a subset of Project Euler problem 8, which doesn't care about digits being consecutive.

I suggest that now would be a great time to add shared test data to https://github.com/exercism/x-common in the form of series.json and get that sorted out in the various tracks. Should also edit the https://github.com/exercism/x-common/blob/master/series.md and https://github.com/exercism/x-common/blob/master/series.yml in whatever manner is necessary to correct any misconceptions.

**Comment by kytrinyx** [comment]
Agreed, a survey + shared test data would be a good next move here.

**Comment by kytrinyx** [comment]
I'm closing this in favor of https://github.com/exercism/x-common/issues/197
