### ISSUE TITLE
Scrabble Score Test

### ISSUE THREAD

**Issue by durrellchamorro** [exercism/xruby#272]
One of the tests for the Scrabble Score exercise looks like this:

```ruby
  def test_scores_are_case_insensitive
    assert_equal 41, Scrabble.new('oxyphenbutazone').score
  end
```

If this is testing it will still calculate scores for words with uppercase and lower case letters, then shouldn't the test look something like this?

```ruby
  def test_scores_are_case_insensitive
    assert_equal 41, Scrabble.new('OxypHenButazoNe').score
  end
```

**Comment by kytrinyx** [comment]
Ah, I think we used to have an all-caps word that was impossible in the regular Scrabble game. We swapped it out with a word that does exist, but forgot to make it all caps.

@kotp What do you think, should we change this to `'OXYPHENBUTAZONE'`? (We don't need any lowercase letters, since the other tests verify that).

**Comment by kotp** [comment]
The old word was capitalized, and an illegal length.  This test uses a valid length word, but no test specifically actually addresses the illegal length that I noticed.

#273 should be more applicable to the actual intent of the test.

**Comment by kotp** [comment]
Thanks @durrellchamorro for bringing this to our attention.

**Comment by durrellchamorro** [comment]
No problem.
