### ISSUE TITLE
Palindrome-products tests unclear

### ISSUE THREAD

**Issue by remcopeereboom** [exercism/xruby#305]
I could not wrap my head around this exercism. It is utterly unclear to me what the point is. The readme is really only one line of any real information (perhaps this warrants an issue at xcommon?), so I turned to the tests and ran into several questions which I think might warrant a refactoring of the tests.

The README says that the goal of the exercism is:

> Write a program that can detect palindrome products in a given range.

Therefore it seems like a good idea to have the tests start by asking for all the pallindrome products, but instead the tests asks for the largest and the smallest. I am not sure if this is the intended behaviour. If it is, the README should be updated, but otherwise the tests should be amended.

The next issue I have is that the factors to test for seem odd. The first tests expect `#largest` to return an object that after calling `#factors` on the returned object in turn yields this rather daunting looking array: `[[[3, 3], [1, 9]], [[1, 9], [3, 3]]]`.

``` ruby
assert_includes [[[3, 3], [1, 9]], [[1, 9], [3, 3]]], largest.factors
```

I think the law of demeter violation is acceptable, but the elements of the array are still surprising; why are there repeats in there (`[3, 3]`)? Why are the arrays doubly nested (i.e. `[ [[3,3], [1,9]], [[1,9], [3,3]] ]`)? Why do we have elements `[1, 9]`, but not `[9, 1]`?

**Comment by petertseng** [comment]
https://github.com/exercism/x-common/issues/208 says you're not the only one... looks like this really could use some work

**Comment by petertseng** [comment]
https://github.com/exercism/x-common/issues/208 and https://github.com/exercism/exercism.io/issues/1979 say you're not the only one... looks like this really could use some work

**Comment by kotp** [comment]
The first element of the array holds two elements, each arrays that represent the factors of 9, and they are identical to the second element of the array, which also holds two elements, each arrays, which, like the first, holds the factors, which are the largest factors.

I do agree that the very first test does not assist very well to getting to 'good'.  I ran it raw, not looking at the test code at all, just iteratively responding to the feedback from the tests... and that one test drove me to write blindly 4 methods aside from initialize.

And @petertseng you can say that again. :)

**Comment by remcopeereboom** [comment]
> The first element of the array holds two elements, each arrays that represent the factors of 9, and they are identical to the second element of the array, which also holds two elements, each arrays, which, like the first, holds the factors, which are the largest factors.

I can see that, but _why_? Why do we have arrays of two pairs? What is the relationship between `[3, 3]` and `[1, 9]` that is missing between `[1, 9]` and `[9, 1]`. Surely if you want all factors, than you want something like `[ [1,9], [3,3], [9,1] ]` instead?

**Comment by remcopeereboom** [comment]
@petertseng I didn't know cross-references accross repositories worked. Thanks!

**Comment by kotp** [comment]
If you have [1, 9], and [9, 1], then you will also want [3, 3] and [3, 3].   But yes, I was a little bit surprised when you used the word "daunting" when I know that you should not find it as such.

**Comment by remcopeereboom** [comment]
> when I know that you should not find it as such.

:-)

> If you have [1, 9], and [9, 1], then you will also want [3, 3] and [3, 3].

I'm not sure that I agree. The pairs (1, 9) and (9, 1) might be considered distinct (and I don't know that they are), but that's surely not the case for (3, 3) and (3, 3)?

**Comment by kotp** [comment]
ES: This is my reasoning to believe that (1, 9), (3, 3), (9, 1) is a partially completed simplified statement that is yet to be completed, or the other way, it is not fully expanded to the original set of factors, showing the individual multiplier and multiplicand (as without, there would be no product), mixing the two ideas still.

It surely is the case for 3 and 3, because it is the case for 1, 9.  The first 3 and the second 3 do not need to be in that order, neither do the 1 and 9. They are distinct values.  Without the other arrangement shown, it is still implied that the first three could be in the second position, while the second three could be in the third spot.

The simplified version of it is to finish simplifying it down to (1, 9), (3, 3) and we understand that each individual value of the pair of digits can be used as a multiplier or multiplicand.  This means that the first three can be a multiplier and the other a multiplicand, or the other way around.  Together they are the factors.  Once you identify them as factors, then you lose the positional distinction of the words multiplier and multiplican, which means that 9 and 1 are identical in that reference regardless of position.  And showing both position possibilities for the individual positions is just that the simplification has not been completed.  In not showing (3, 3) and (3, 3) is a further hint that the simplification is partially complete.

**Comment by kytrinyx** [comment]
> I have the distinct feeling that the tests are railroading a particular solution to the problem.

That is definitely a possibility, and overall I'd like to improve exercises so that they don't push towards specific implementations.

**Comment by rbndickson** [comment]
Just adding that I was confused by this exercise and the tests too.

**Comment by hilary** [comment]
Much as I dislike this exercise, the last meaningful activity was almost a year ago, so I'm closing this issue.
