### ISSUE TITLE
Class level methods making it hard to extract private methods?

### ISSUE THREAD

**Issue by swanson** [exercism/xruby#309]
I reviewed some exercises after a long break from using the site and found that some of the early Ruby track are now using class methods for the public API: `Complement.of_dna`, `Hamming.compute`, etc.

I can appreciate that a single class method might be easier to understand than an initializer and an instance method, but some of the solutions I was reviewing would benefit from extracting private methods (which are not the easiest to do for class level methods).

Has anyone else experienced this?

**Comment by Cohen-Carlisle** [comment]
I've never really noticed that pain. I usually just use `private_class_method`, but another option is to use:
```ruby
module Foo
  class << self
    def foo(arg)
      bar(arg)
    end

    private

    def bar(arg)
      arg.to_s
    end

  end # class << self
end # module Foo
```

**Comment by kytrinyx** [comment]
The private class method works if you don't have state. If you do have state there's a huge risk of race conditions. If I need more methods I often do this:

```
class Foo
  def self.bar(arg)
    new(arg).bar
  end

  def initialize(arg)
    # ...
  end

  def bar
    # ...
  end

  private

  # all the private methods
end
```

**Comment by kotp** [comment]
For many of the exercises if the tests do not explicitly force a class, I will use a Module.  For clock, this doesn't present until you need two of them... then it forces a class solution.

Hopefully we are never forcing a solution and leave it open for creativity.  I know that this goal has not been achieved yet for many exercises, and this is usually forced due to the tests themselves making some decisions.

I just checked Hamming, to see if your assessment seems accurate, there is no indication of any class being imposed.

```ruby
module Hamming
  VERSION = 1
  def compute(strand_a, strand_b)
    raise ArgumentError unless strand_a.size == strand_b.size
    [strand_a.size, strand_b.size].min.times.collect.count do |n|
      strand_a[n] != strand_b[n]
    end
  end
end
Hamming.extend(Hamming)
```

Nothing forcing class use here at all.

You stated that you are reviewing solutions, so perhaps the code is presenting problems because of the decisions they made to solve it, rather than the tests.

**Comment by swanson** [comment]
Thanks for weighing in -- sounds like it's not a widespread issue. Appreciate the discussion :)

**Comment by Cohen-Carlisle** [comment]
@kytrinyx and @kotp melted my brain a little.
