### ISSUE TITLE
What do you think of ordering config.json problems alphabetically?

### ISSUE THREAD

**Issue by tute** [exercism/xruby#320]
While reading http://www.sitepoint.com/exorcise-your-newbie-demons-by-contributing-to-exercism/, I came across the following step:

> Add the slug of the exercise to the `problems` array. It’s hard to say where it should go, so unless you have a better idea, stick it anywhere in the second half.

What do you think of ordering that list alphabetically? Two benefits are:

1. People might notice the deliberate order of the dozens of exercises, knowing where to put their new submission
1. It's easier to scan the list to check if a given exercise is present or not, or if there are duplicates

A possible drawback is:

1. It might feel too nitpicky to receive that comment in the first PRs that we send if we don't do it that way
1. It might make people feel that there is an "important" reason for this order, but it's just a convention

**Comment by bernardoamc** [comment]
Having this list sorted alphabetically would be nice for contributors, but it wouldn't make sense for people trying to learn a new language if the knowledge gap between problems are too big, right?

I think this list should be sorted by the complexity of each problem (this is a difficult task), the easier problem being in the first position.

**Comment by tute** [comment]
> Having this list sorted alphabetically would be nice for contributors, but it wouldn't make sense for people trying to learn a new language if the knowledge gap between problems are too big, right?

That's true. Though I found that sometimes "following a script" enables people to make changes more swiftly (overcoming the fear of "breaking" something). I am new to the Exercism community, so I'm not sure if that applies here as well.

**Comment by kotp** [comment]
Welcome to the community!  Glad to see you are thinking about this, really!

Definitely not by alphabetical order.  It is perhaps trivial enough to pipe the actual file through sed for an alphabetical temporary listing, or otherwise manipulate it in comparison of another similar file, perhaps for finding out what is missing... Combining with a diff tool in the pipe makes this trivial, for example.  Of course, this entire paragraph assumes some level of knowledge, and so trivial may not apply, if you haven't solved that problem yet, or at least a few times.

Order of complexity is preferred, though, yes, it is difficult to do, especially when the ordering for one language can be very different for another language.  Some things are simply trivial for a language given a certain problem, and yet complicated in another (Yes, "Hello World"!)

If it were alphabetical, we would likely need to add another field to the file, a weight, in order to present them in the complexity order.  As it is, it is in a presumed order of complexity, and to some extent, separating similar problems (math problems, word problems, etc) from each other.  Doing so, adds some complexity in how the application decides which is next.

And, like you mentioned, having the list in the order it is in, doesn't imply more than it should.  The order is important because it is ordered that way.  To order it in another way is left as an exercise for the person that, for unknown reasons, may need it to be alphabetical.

**Comment by bernardoamc** [comment]
> That's true. Though I found that sometimes "following a script" enables people to make changes more swiftly (overcoming the fear of "breaking" something). I am new to the Exercism community, so I'm not sure if that applies here as well.

Yeah, I totally agree with you. Maybe we could explain to the contributors why the name should go to the second half of the list instead of telling them to just do it, this way if the contributor knows a similar problem as the one he is solving he can group the names without this fear of breaking something.

For example:

```ruby
# config.json
A
B
C
```

If the contributor knows that the problem `D` he is implementing is similar to `B`, he can do this without fear:

```ruby
# config.json
A
B
D
C
```

**Comment by tute** [comment]
When I first read "It’s hard to say where it should go", I somehow thought there's no special order, but now I understand that it's actually not easy! I'm good with how that document is written, and with the order not being alphabetical.

Code reviews will help each contributor put it around the section where it best fits.

Thank you both for your input! :)

**Comment by kytrinyx** [comment]
This was a great discussion. I'm going to ask the editors at sitepoint if I can tweak that part of the article to clarify.
