### ISSUE TITLE
Discussion: Location of BookKeeping

### ISSUE THREAD

**Issue by Insti** [exercism/xruby#360]
Is there a way to encourage people to put the BookKeeping module at the bottom of their code rather than at the top? It's a lot easier for reviewers if the first thing they see is the important part of the code.

**Comment by Insti** [comment]
The current wording is:
>   Define a constant named VERSION inside of the top level BookKeeping module.

Having 'top level' in there is likely to prompt people to put it at the top of the code.
Perhaps adding 'at the bottom of your code' might help.

**Comment by kytrinyx** [comment]
Agreed, we could definitely change the wording (also agreed: we should encourage people to stick it at the bottom of their solution!).

**Comment by kotp** [comment]
Would that not be part of the conversation in review?  I could imagine this in a review discussion:

"I find it easier if all of our constants that aren't directly important to our problem at hand, if the constants communicate on time.  Because the BookKeeping is not important to our <whatever problem>, maybe it should be after all of our code, or in <whatever> location." -- KOTP

"I think it is important that we place the BookKeeping module after our solution to the problem, so I would have stuck it after <whatever constant under tests here>.  I feel that it is easier for reviewers to just skip down to verify that what they are reviewing is in fact written to the current tests" -- George

"We should encourage people to stick it at the bottom of our solution" -- Kytrinyx

I think it is important to talk about this, I think it is a great place to introduce that conversation.

There is also value in seeing it right away, as it indicates if the code will or even should pass the current version of the tests.  It may be irritating writing a review, seeing the code first, getting your response together, and then realizing "TLDR, this version is not going to (or may not) pass the current test version 9, but did pass at version 1".  That is a little late to be telling me that little useful tidbit of knowledge.

Perhaps, the encouragement to do so is as we are reviewing the solution.  It is where we talk about where to put our attr_* our other constants, how we organize our methods, or modules our classes, our class variables and etc..  Why not talk about the book keeping in the reviews?

**Comment by kytrinyx** [comment]
I never thought of the bookkeeping as something to talk about in the reviews. Honestly, if we could do without it, I would. This feels very tangential to the problem at hand.

Reviewers really should get in the habit of looking for the bookkeeping module, and they probably will if they review any more than three or four solutions. As a reviewer, though, I imagine that I would find the bookkeeping stuff to be kind of noisy and irrelevant. I'd rather have the important code up front.

All of this said: I don't actually feel very strongly about this, and I haven't reviewed much in Ruby lately, so I don't expect that I'll have a very accurate gut reaction about the situation.
