### ISSUE TITLE
Any way to deal with unwanted version bumps while iterating on a generator?

### ISSUE THREAD

**Issue by petertseng** [exercism/xruby#486]
I know there's already #485 open, but that one is about missing files, whereas this one is about what to do when the files are in place.

My problem statement is: When I am first making a generator or responding to feedback about a new generator, I will often have to iterate on it a lot. My personal style is that I regenerate the tests after a change I make to the example.tt, so that I can be sure that everything still works. This bumps the test version, which I didn't want in this case.

Current workaround: Manually decrement the version in the `.version` file before running `generate`, so that the version stays the same during this operation.

I can also envision perhaps a command-line flag to `generate` that will refrain from bumping the version. Depends on what behaviour should be the default (to bump or not to bump).

So with this issue I am wondering whether this experience is shared enough to warrant a solution like that flag. If it's unique to me I'll probably just continue with my workaround.

**Comment by bmulvihill** [comment]
@petertseng I have had the same issue and usually have to remember to set the version to the correct number before opening the PR.  A flag might be useful

Something like:
`bin/generate EXERCISE --skip-version`

**Comment by Insti** [comment]
This issue is **very** close to the top of my todo list.

**Comment by Insti** [comment]
My current workflow is to comment out the increment lines in the `bin/generator`  file while I'm developing.

**Comment by petertseng** [comment]
> My current workflow is to comment out the increment lines in the `bin/generator` file while I'm developing.

I tried this out, and then found that a great many of the `example.tt` files use `assert_equal <%= version.next %>, BookKeeping::VERSION` (all except `connect/example.tt` in fact!)

So this successfully stops the `.version` and `example.rb` files from being modified, though the generated test file still has a bumped version, argh!

I hacked around it with:

```ruby
  def version
    @version ||= File.read(path_to('.version')).strip.to_i - 1
  end
```

but it would be a bit tricky to understand "why is 1 being subtracted?" if this solution were taken. Kind of makes me wish the `example.tt` were using plain `version` instead of `version.next`, but that's a bit of an invasive change.

**Comment by Insti** [comment]
I have several ideas about this, not sure just yet which is best.

 1. Add a flag to freeze the current version (-f / --freeze or -s / --skip-version)
 1. Default to NOT update and add a flag to update the version (-u / --update-version) 
 1. Use an environment variable to toggle updating.
 1. Compare the git sha1 hashes to detect json changes and only update version if json has changed. (And have flag to manually force an update.)

I don't think we should be too worried about making breaking changes, since there isn't anyone updating generators who won't be reading this thread, and we can easily update the documentation.

I think I like number 4 the most.

Opinions?

**Comment by kotp** [comment]
When I have done this, I have a script that just does a `git checkout exericise/active/{filelist}` to bring them back down.

**Comment by kotp** [comment]
@petertseng What if we named that negative 1 to "prior_version" then it would say what it is doing.

**Comment by kotp** [comment]
I prefer what peter is doing, I think.  Have it pre-set the version file.  Why the exception on the one exercise "connect"?

**Comment by petertseng** [comment]
Another interesting thing to consider - however this is solved, I prefer "if the version number is going to stay the same, do not write the file at all" over "always write the file even if it results in no change since we kept the version number the same", since my editor warns me if something other than itself has changed the file in the meantime.

> I have several ideas about this

It seems like 4 (auto-detect whether version bump needed based on sha) is a great benefit, as there should be no risk of people forgetting to bump when necessary, while handling the case of repeatedly re-generating based on the same set of tests (when iterating)!

I would consider 1 (add flag to not update) to be a worthy alternative in the meantime. Between 1 and 2 I chose to default to updating because I *suspect* that is the more usual reason to modify a generated test file - iterating on the generator seems to be the rarer case, though I may be wrong - y'all naturally know your track better than I do.

**Comment by Insti** [comment]
>  "if the version number is going to stay the same, do not write the file at all" 

It is not uncommon for the file to be updated without the version number changing.
The version number should only change if there is a change in the test inputs/outputs.

Updating to fix a typo in a test name, a Rubocop warning or adding better failure messages would not cause a version update.

**Comment by kotp** [comment]
The change in warning does, and the better failure messages may cause a version update, if the conversation changes, we may be scratching our heads wondering which version of the test they are running against... when I say we, I mean anyone reviewing that does not have that problem.  I would say a bump may still be in order, though it may be a fractional number, such as `2.1`.  This would be a manual set, rather than an full increment increase.

If this were to happen, we would need to for integer math which at the moment is ignored.  Any introduction of a float would continue to influence that number.

**Comment by Insti** [comment]
I've started working on this. There's a few things I need to put in place first: #503

**Comment by Insti** [comment]
Version freezing option is present in: #522
(as is only writing out changed files.)

**Comment by Insti** [comment]
#522 Has now been merged so I'm marking this as resolved.

Using the `--freeze` command line option will cause the version number to not be incremented when regenerating tests.

`bin/generate --freeze exercise-name`
