### ISSUE TITLE
Document how to get coloured output in tests in SETUP.md

### ISSUE THREAD

**Issue by JikkuJose** [exercism/xruby#74]
I am using `minitest-reporters` gem to colour the test output, I think adding that would make it easier for many; any objections in submitting a pull request?

The only down side I see is that users needs to install the dependency; may have to update the instructions elsewhere.

**Comment by kytrinyx** [comment]
Unfortunately colours don't work on Windows, it just outputs very ugly meta characters.

**Comment by kotp** [comment]
It can output colors in Windows, but we could do a platform check to shut it off for Windows users.

And the characters that it outputs are ANSI characters, just to know what to search for, if you are curious.

**Comment by kytrinyx** [comment]
Thanks @kotp -- Maybe the gem that didn't work on windows was pride. I'd be open to a pull request that adds something like that optionally -- meaning don't bail and don't complain if it triggers a `LoadError`.

If it works for Windows I don't see a reason to shut it off for Windows users. I'd love to have someone test that, though, to verify before we change 70 test suites :)

**Comment by kotp** [comment]
I think ANSI support is an environment question so we shouldn't worry too much about it.

Since we have to open the test files anyway, would we just document that if you want colored tests, you can insert the line:

    require 'minitest/pride''

As we are using minitest already and minitest comes with pride automatically.  No gem required.

**Comment by JikkuJose** [comment]
@kytrinyx @kotp Then let me see if I can test `minitest-reporters` in Windows; frankly have never worked in Ruby on Windows yet! It seems the best option may to just disable it in Windows?

**Off topic**: Also, isn't the usage `MiniTest::Unit::TestCaset` [deprecated](http://stackoverflow.com/a/17461423/2602869), what about changing to `Minitest::Test`?

**Comment by kotp** [comment]
It won't be so much 'disabling it' on Windows, but making it an opt-in which is not hard to do, you simply install a gem or require the minitest/pride library.

There is already discussion on the syntax of the Minitest unit tests.

**Comment by kytrinyx** [comment]
The discussion about minitest versions is here: https://github.com/exercism/xruby/pull/71

**Comment by Carpetsmoker** [comment]
I also have the problem that many colours don't work very well on white backgrounds; I regularly get things like bright yellow text on a white background :-/ A light (white) background colour is the default for many terminal emulators (such as `xterm`, `gnome-terminal`, `xrvt`, etc).

I don't know what MiniTest's colours are, since I only used rspec before, but in the interest of "safe defaults that work for as many people as possible" it's something to consider.

**Comment by kytrinyx** [comment]
Yeah, I lean towards documenting in the readme how to get colours, and then leaving it up to the person to add it if they want.

**Comment by kotp** [comment]
:+1:  on leaving it up to the person.  It provides that learning as well.  And avoids a potentially troubling domain, in that assuming colors in a terminal or a graphical terminal or a terminal emulator (even having to list those three means it is more complex than initially may believed) and applying it to the individual eyes of people is not a simple subject.

**Comment by kytrinyx** [comment]
I've changed the title of this issue to reflect the discussion we've had.

If this documentation gets added to `SETUP.md` in the root of this repository, then that will be distributed with each of the README files for each problem in the Ruby track.

**Comment by kotp** [comment]
It has been a while.  Leaving it up to the individual, and closing the issue.
