### ISSUE TITLE
Using the Prime module on the nth-prime test

### ISSUE THREAD

**Issue by Carpetsmoker** [exercism/xruby#95]
Do we want to encourage the usage of Ruby's standard `Prime` module for the nth-prime test?

I wanted to make a patch to prevent using the `Prime` module, as I would consider that to be slightly cheating and defeating the purpose of the exercise, but the `example.rb` seems to use it as well ...

**Comment by kotp** [comment]
I saw that in recent solution, and I thought the same thing.  But only if the [readme](https://github.com/exercism/x-common/blob/master/nth-prime.yml) states to use built in language items only, otherwise in my opinion, it would be fair game.

https://github.com/exercism/xruby/tree/master/nth-prime for ease of reference.

And for ease of reference to which '[example.rb](https://github.com/exercism/xruby/blob/master/nth-prime/example.rb)' uses it just in case that changes as well. 

This isn't to say that you can't test for it and report encouragement.  But again, this may be a function of the 'nitpick' activity.

**Comment by kytrinyx** [comment]
> Do we want to encourage the usage of Ruby's standard Prime module for the nth-prime test?

No, I would want to discourage that. I would welcome a patch that prevents the use of `Prime`. I already did this in `Gigasecond` to prevent the use of date.

**Comment by kotp** [comment]
Looks like it is adequately fixed.
